name: food_scale
description: "FoodScale App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  flutter_slidable: ^4.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/ic_launcher.png
    - assets/ic_launcher_foreground.png
    - assets/data.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600

    - family: MontserratAlternates
      fonts:
        - asset: fonts/MontserratAlternates-SemiBold.ttf
          weight: 600

    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  adaptive_icon_background: "#000000"  
